// <auto-generated />
namespace Libraryman.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReturnedBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReturnedBook));
        
        string IMigrationMetadata.Id
        {
            get { return "201709071335235_AddReturnedBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
